all: HighestInt ProductOfEven Drawing BarChart

HighestInt:
	g++ highestint.cpp -o ../build/HighestInt

ProductOfEven:
	g++ productofeven.cpp -o ../build/ProductOfEven

Drawing:
	g++ drawing.cpp -o ../build/Drawing

BarChart:
	g++ barchart.cpp -o ../build/BarChart
