all: Gradebook GradebookSentinel GradebookSingle

Gradebook:
	g++ Gradebook.h Gradebook.cpp Main.cpp -o ../build/Gradebook

GradebookSentinel:
	g++ Gradebook.h GradebookSentinel.cpp Main.cpp -o ../build/GradebookSentinel

GradebookSingle:
	g++ GradebookSingle.cpp -o ../build/GradebookSingle
