all: Die Enum C11die defaultargument maximum

Die:
	g++ die.cpp -std=c++11 -o ../build/die

Enum:
	g++ enum.cpp -std=c++11 -o ../build/enum

C11die:
	g++ c11die.cpp -std=c++11 -o ../build/c11die

defaultargument:
	g++ defaultargument.cpp -std=c++11 -o ../build/defaultargument

maximum:
	g++ maximum.cpp -std=c++11 -o ../build/maximum
